load("@rules_ruby//ruby:defs.bzl", "rb_binary")

# rb_library(
#     name = "uptime",
#     srcs = ["uptime.rb"],
# )

# rb_binary(
#     name = "show-uptime",
#     args = ["uptime.rb"],
#     deps = [":uptime"],
# )

rb_binary(
    name = "uptime",
    args = ["src/rb/uptime.rb"],
)
